In [32]:

import math
import numpy as np

arr = np.array([[1, 1, 0], [0, 1, 0], [0, 0, 1]])

arrlist = [arr] * 100

# arrlist

In [33]:

print(np.dot(arr, arr))

[[1 2 0]
 [0 1 0]
 [0 0 1]]


In [34]:

from functools import reduce

print(reduce(lambda mul, x: np.dot(x, mul), arrlist))

[[  1 100   0]
 [  0   1   0]
 [  0   0   1]]
